### ISSUE TITLE
Accidental Mis-categorization

### ISSUE THREAD

**Issue by zkhcohen** [alectron/MusicBee_TagHierarchies#3]
https://github.com/alectron/MusicBee_TagHierarchies/blob/a7ebea3700c1872613e27f12c80210485d32c98e/Genres/Community%20Versions/(Community)%20MusicBee_3Layer.txt#L123

Hey,

It looks like you committed a version built off of my old, incorrect version where I has miscategorized Disco. Now the layer2 and layer3 community versions are out of sync.

The new genre additions look great, however. 

I would also suggest the addition of "Indie R&B" and "Alternative R&B" (quickly growing genres on Spotify) if you decide to re-commit.

**Comment by alectron** [comment]
Thanks for the heads up!!  Correcting this now

**Comment by alectron** [comment]
Fixed & commited
